# Specify the docker image to use (only used if using docker runners)
# See: http://doc.gitlab.com/ee/ci/docker/using_docker_images.html
image: ubuntu:16.04

# Define commands that run before each job's script
before_script:
  - apt-get update
  - apt-get install -y g++ cmake git

build:
    script:
        - mkdir bin && mkdir build && cd build
        - cmake ..
        - make
        - make test
    artifacts:
        paths:
            - build/test_detail.json
        expire_in: 1 week
